language: android
sudo: required
jdk: oraclejdk8

notifications:
  email:
  - adamluissean@gmail.com

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/daemon
  - $HOME/.gradle/native
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

env:
 global:
 - ANDROID_API=26
 - EMULATOR_API=21
 - ANDROID_BUILD_TOOLS=26.0.0
 - ADB_INSTALL_TIMEOUT=15 # minutes

before_script:
  - chmod +x gradlew
  - android list target
  - echo no | android create avd --force -n test -k "system-images;android-25;google_apis;x86"
  - emulator -avd AndroidEmulator0 -no-skin -no-audio -no-window & #Start emulator

android:
  update_sdk: true  #Check for the updates each time you run the build.
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository # for design library
  - addon-google_apis-google-19 # google play services
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-android-19
  - sys-img-armeabi-v7a-android-21
  - sys-img-armeabi-v7a-android-23
  - sys-img-armeabi-v7a-android-24
  - sys-img-armeabi-v7a-android-25
  - sys-img-x86-android-19
  - sys-img-x86-android-21
  - sys-img-x86-android-23
  - sys-img-x86-android-24
  - sys-img-x86-android-25

 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- ./gradlew dependencies || true

script:
- echo "Travis branch is $TRAVIS_BRANCH"
- android-wait-for-emulator
- adb devices
- adb shell input keyevent 82 &
- "./gradlew clean build -Pbuild=dev connectedAndroidTest -PdisablePreDex --stacktrace"
